USE mysql;
CREATE SCHEMA bto_data;
DROP TABLE IF EXISTS bto_data.species_lookup;
CREATE TABLE bto_data.species_lookup (
    SPEC_CODE INT NOT NULL PRIMARY KEY,
    ENGLISH_NAME VARCHAR(255) NOT NULL,
    SCIENTIFIC_NAME VARCHAR(255) NOT NULL,
    TAXONOMIC_RANK VARCHAR(100) NOT NULL
);
DROP TABLE IF EXISTS bto_data.distributions;
CREATE TABLE bto_data.distributions (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATE_PERIOD VARCHAR(20) NOT NULL,
    SEASON VARCHAR(1),
    SPEC_CODE INT NOT NULL,
    GRID_REF VARCHAR(10),
    ISLAND VARCHAR(10),
    RESOLUTION INT,
    N_TENKMS INT,
    STATUS VARCHAR(20)
);
ALTER TABLE bto_data.distributions
ADd CONSTRAINT fk_dist_species
FOREIGN KEY(SPEC_CODE)
REFERENCES bto_data.species_lookup(SPEC_CODE);
